Feature/nonhttp
UKCloud/openshift-heat pull request #90
Opened 2019-01-21 17:43 UTC by koneill94

Rebased for 3.11 and tested with a 3.11 deployment

2019-02-20 17:25 UTC, MudasarUKCloud approved these changes
Approving this PR.

2019-02-21 14:49 UTC, benbacon requested changes
Minor change required, otherwise looks good

2019-02-21 14:49 UTC, benbacon commented on environment_example.yaml
>    # Example of passing in configuration for SSO
Can you move this to line 68?

2019-02-21 14:56 UTC, benbacon commented
Looks good

2019-02-21 14:57 UTC, benbacon approved these changes

2019-02-26 15:50 UTC, stevemul approved these changes
lgtm

2019-02-26 15:52 UTC, merged